"""add_ml_tables

Revision ID: 4315cc988041
Revises: 054a31680622
Create Date: 2026-03-14 15:18:40.068900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4315cc988041'
down_revision: Union[str, Sequence[str], None] = '054a31680622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('mlflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circuit_corners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('corner_number', sa.Integer(), nullable=False),
    sa.Column('entry_distance_m', sa.Float(), nullable=False),
    sa.Column('apex_distance_m', sa.Float(), nullable=False),
    sa.Column('exit_distance_m', sa.Float(), nullable=False),
    sa.Column('entry_speed_median', sa.Float(), nullable=True),
    sa.Column('apex_speed_median', sa.Float(), nullable=True),
    sa.Column('exit_speed_median', sa.Float(), nullable=True),
    sa.Column('corner_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circuit_id', 'corner_number', name='uq_circuit_corner')
    )
    op.create_table('driver_dna_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('feature_vector', sa.Text(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('cluster_label', sa.String(length=100), nullable=True),
    sa.Column('pca_x', sa.Float(), nullable=True),
    sa.Column('pca_y', sa.Float(), nullable=True),
    sa.Column('tsne_x', sa.Float(), nullable=True),
    sa.Column('tsne_y', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'season_id', name='uq_driver_dna_feature')
    )
    op.create_table('driver_similarities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_a_id', sa.Integer(), nullable=False),
    sa.Column('driver_b_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('cosine_similarity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['driver_a_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['driver_b_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_a_id', 'driver_b_id', 'season_id', name='uq_driver_similarity')
    )
    op.create_table('driver_corner_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('corner_id', sa.Integer(), nullable=False),
    sa.Column('brake_point_m', sa.Float(), nullable=True),
    sa.Column('min_speed', sa.Float(), nullable=True),
    sa.Column('entry_speed', sa.Float(), nullable=True),
    sa.Column('exit_speed', sa.Float(), nullable=True),
    sa.Column('throttle_on_distance', sa.Float(), nullable=True),
    sa.Column('trail_braking_score', sa.Float(), nullable=True),
    sa.Column('gear_at_apex', sa.Integer(), nullable=True),
    sa.Column('time_in_corner_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corner_id'], ['circuit_corners.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id', 'corner_id', name='uq_driver_corner_stat')
    )
    op.create_table('tyre_deg_curves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('stint_number', sa.Integer(), nullable=False),
    sa.Column('compound', sa.String(length=20), nullable=True),
    sa.Column('model_type', sa.String(length=20), nullable=True),
    sa.Column('coefficients', sa.Text(), nullable=True),
    sa.Column('r_squared', sa.Float(), nullable=True),
    sa.Column('deg_rate_ms_per_lap', sa.Float(), nullable=True),
    sa.Column('predicted_cliff_lap', sa.Integer(), nullable=True),
    sa.Column('num_laps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id', 'stint_number', name='uq_tyre_deg_curve')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tyre_deg_curves')
    op.drop_table('driver_corner_stats')
    op.drop_table('driver_similarities')
    op.drop_table('driver_dna_features')
    op.drop_table('circuit_corners')
    op.drop_table('ml_runs')
    # ### end Alembic commands ###
